# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tick.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntick.proto\x12\x06nse.v1\"\x96\x02\n\x04Tick\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x15\n\rtimestamp_ist\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0e\n\x06volume\x18\x04 \x01(\x04\x12\x1f\n\x04side\x18\x05 \x01(\x0e\x32\x11.nse.v1.Tick.Side\x12\x10\n\x08\x65xchange\x18\x06 \x01(\t\x12\x12\n\nsession_id\x18\x07 \x01(\t\x12\x0b\n\x03seq\x18\x08 \x01(\x04\x12\x0c\n\x04name\x18\t \x01(\t\x12\x0e\n\x06sector\x18\n \x01(\t\x12\x10\n\x08industry\x18\x0b \x01(\t\x12\x13\n\x0bmcap_bucket\x18\x0c \x01(\t\"/\n\x04Side\x12\x14\n\x10SIDE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tick_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TICK']._serialized_start=23
  _globals['_TICK']._serialized_end=301
  _globals['_TICK_SIDE']._serialized_start=254
  _globals['_TICK_SIDE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
