# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbar.proto\x12\x06nse.v1\"\xbb\x01\n\x03\x42\x61r\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61r_size\x18\x02 \x01(\t\x12\x14\n\x0cwindow_start\x18\x03 \x01(\t\x12\x12\n\nwindow_end\x18\x04 \x01(\t\x12\x0c\n\x04open\x18\x05 \x01(\x01\x12\x0c\n\x04high\x18\x06 \x01(\x01\x12\x0b\n\x03low\x18\x07 \x01(\x01\x12\r\n\x05\x63lose\x18\x08 \x01(\x01\x12\x0e\n\x06volume\x18\t \x01(\x04\x12\x0c\n\x04vwap\x18\n \x01(\x01\x12\x12\n\ntick_count\x18\x0b \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BAR']._serialized_start=22
  _globals['_BAR']._serialized_end=209
# @@protoc_insertion_point(module_scope)
